# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: git@github.com:frkl-dev/python-project-template.git
anaconda_user: freckles
email: markus@frkl.dev
full_name: Markus Binsteiner
github_user: makkus
project_licenses:
- 0BSD
project_name: template_test
project_short_description: A test project.
python_min_version: '3.14'
