name: "windows tests for 'template_test'"
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test-windows:
    name: pytest on windows
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: ["3.14"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ matrix.python_version }}
      - name: Test with pytest
        run: make tests
